import { useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { Link } from 'react-router'
import { incidentApi, type AiReviewPublicationRequest, type IncidentSearchResult, type AiRun, type AiTask, type AnalysisReport } from '@/lib/incidents'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { useAuth } from '@/components/Auth'
import { SemanticRunReview } from '@/components/IncidentSemanticReview'

const selectClass = 'mt-1.5 h-9 w-full rounded-md border border-input bg-background px-2.5 text-sm outline-none focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/40 disabled:opacity-50'
const evidenceLinkClass = 'rounded-sm font-mono text-xs underline decoration-border underline-offset-4 hover:decoration-current focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring'

const TASKS: AiTask[] = ['question', 'investigation', 'summary', 'recovery', 'note']
export function OpenAiPanel({ report, enabled, reasons, onEvidence }: { report: AnalysisReport; enabled: boolean; reasons: string[]; onEvidence: (id: string) => void }) {
  const { user } = useAuth()
  const [task, setTask] = useState<AiTask>('question')
  const [question, setQuestion] = useState('What does the available evidence support?')
  const [retrievalMode, setRetrievalMode] = useState<'evidence_only' | 'lexical' | 'hybrid'>('evidence_only')
  const [corpusId, setCorpusId] = useState('')
  const corpora = useQuery({ queryKey: ['corpora'], queryFn: incidentApi.corpora, enabled })
  const selectedCorpus = corpusId || corpora.data?.items[0]?.id || ''
  const [requestKey, setRequestKey] = useState('')
  const [run, setRun] = useState<AiRun | null>(null)
  const create = useMutation({ mutationFn: (key: string) => incidentApi.createAiRun(report.id, { idempotency_key: key, task, question: question.trim(), retrieval_mode: retrievalMode, ...(retrievalMode !== 'evidence_only' ? { corpus_id: selectedCorpus } : {}) }), onSuccess: setRun })
  const recover = useMutation({ mutationFn: () => incidentApi.aiRunByRequest(requestKey), onSuccess: setRun })
  const status = useQuery({ queryKey: ['ai-run', run?.id], queryFn: () => incidentApi.aiRun(run!.id), enabled: run?.status === 'RUNNING', refetchInterval: (query) => query.state.data?.status === 'RUNNING' ? 2000 : false })
  const current = status.data ?? run
  const output = current?.status === 'COMPLETED' ? current.result?.output : undefined
  const claims = [
    ...(output?.claims?.map((claim, index) => ({ claim, path: `claims.${index}` })) ?? []),
    ...(output?.selected_claims?.map((claim, index) => ({ claim, path: `selected_claims.${index}` })) ?? []),
    ...(output?.hypotheses?.map((item, index) => ({ claim: item.explanation, path: `hypotheses.${index}.explanation` })) ?? []),
    ...(output?.assertions?.map((item, index) => ({ claim: item.assertion, path: `assertions.${index}.assertion` })) ?? []),
  ]
  return <section className="space-y-4 rounded-lg border bg-card p-5"><h2 className="text-base font-semibold">OpenAI draft</h2><p className="text-xs text-zinc-600">Drafts require human review. Calculated metrics and uncertainty remain attached to every draft.</p>
    {!enabled && <p role="status" className="text-sm text-amber-900">{reasons.join(' ')}</p>}
    <div className="grid gap-4"><label className="block text-xs font-medium">Task<select aria-label="OpenAI task" className={selectClass} value={task} onChange={(event) => { const value = TASKS.find((item) => item === event.target.value); if (value) setTask(value) }}>{TASKS.map((item) => <option key={item} value={item}>{item[0].toUpperCase() + item.slice(1)}</option>)}</select></label></div>
    <label className="block text-xs">Evidence retrieval<select className={selectClass} value={retrievalMode} onChange={(event) => setRetrievalMode(event.target.value === 'hybrid' ? 'hybrid' : event.target.value === 'lexical' ? 'lexical' : 'evidence_only')}><option value="evidence_only">Current evidence only</option><option value="lexical">Lexical historical retrieval · no query embedding</option><option value="hybrid">Hybrid historical retrieval</option></select></label>{retrievalMode !== 'evidence_only' && <label className="block text-xs">Corpus release<select className={selectClass} value={selectedCorpus} disabled={corpora.isPending || !corpora.data?.items.length} onChange={(event) => setCorpusId(event.target.value)}>{!corpora.data?.items.length && <option value="">{corpora.isPending ? 'Loading corpus releases…' : 'No published corpus available'}</option>}{corpora.data?.items.map((item) => <option key={item.id} value={item.id}>{item.id}</option>)}</select></label>}
    {retrievalMode !== 'evidence_only' && !corpora.isPending && !selectedCorpus && <p role="status" className="text-xs text-muted-foreground">No published corpus available. Use current evidence only.</p>}
    {retrievalMode !== 'evidence_only' && corpora.isError && <p role="alert" className="text-xs text-red-800">Corpus releases could not be loaded: {corpora.error.message}</p>}
    {task === 'note' && <p className="text-xs text-zinc-600">Extract observations from the pinned source evidence. Confirm draft assertions before publication.</p>}
    <label className="block text-xs font-medium">Question or task instruction<textarea className="mt-1.5 min-h-24 w-full resize-y rounded-md border border-input bg-background p-3 text-sm leading-relaxed outline-none focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/40" value={question} maxLength={500} onChange={(event) => setQuestion(event.target.value)} /></label>
    <Button size="sm" disabled={!enabled || create.isPending || current?.status === 'RUNNING' || question.trim().length < 3 || retrievalMode !== 'evidence_only' && !selectedCorpus} onClick={() => { const key = crypto.randomUUID(); setRequestKey(key); setRun(null); create.mutate(key) }}>{create.isPending ? 'Request in progress…' : current?.status === 'RUNNING' ? 'Draft running…' : 'Generate draft'}</Button>
    <details className="border-t pt-4"><summary className="cursor-pointer text-xs font-medium focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring">Recover an interrupted request</summary><div className="mt-3 space-y-3"><label className="block space-y-1.5 text-xs">Request identity<Input aria-label="Request identity" value={requestKey} onChange={(event) => setRequestKey(event.target.value)} /></label><Button size="sm" variant="outline" disabled={!user || !requestKey.trim() || recover.isPending} onClick={() => recover.mutate()}>{recover.isPending ? 'Looking up request…' : 'Recover existing request'}</Button><p className="text-xs text-zinc-500">A lookup retrieves the original operation without starting another paid request. Keep this identity to recover after a connection interruption.</p></div></details>
    {(create.error || recover.error || status.error) && <p role="alert" className="text-sm text-red-700">{(create.error ?? recover.error ?? status.error)?.message}</p>}
    {current && <div aria-live="polite" className="space-y-3 border-t pt-3"><p className="text-xs font-semibold">{current.status} · {current.configuration?.generation_model ?? 'OpenAI'}{output ? ' · Awaiting human review' : ''}</p>{current.result?.reason && <p>{current.result.reason}</p>}{current.result?.errors?.map((error, index) => <p role="alert" key={index} className="text-sm text-red-700">{error === 'MODEL_ACCESS_UNAVAILABLE' ? 'The configured model is unavailable to this API project.' : error === 'PROVIDER_TEMPORARILY_UNAVAILABLE' ? 'The provider is temporarily unavailable.' : error}</p>)}
      {claims.map(({ claim, path }) => <article key={path} className="space-y-2 border-t py-4"><p className="text-sm">{claim.text}</p><div className="flex flex-wrap gap-2">{claim.evidence_ids.map((id) => <button key={id} className={evidenceLinkClass} onClick={() => onEvidence(id)}>{id}</button>)}</div>{claim.historical_refs?.map((id) => { const excerpt = current.packet?.historical_evidence?.find((item) => item.id === id); return <blockquote key={id} className="border-l border-border pl-3 text-xs leading-relaxed"><strong>Historical excerpt · {id}:</strong> {excerpt?.text ?? excerpt?.excerpt ?? 'Unavailable'}</blockquote> })}{claim.metric_ids.map((id) => { const metric = claim.rendered_metrics?.find((item) => item.id === id) ?? current.packet?.metrics?.find((item) => item.id === id); return <p key={id} className="text-xs"><strong>{id}:</strong> {metric ? `${metric.value ?? 'Unavailable'} ${metric.unit}` : 'Metric reference unavailable'}{metric?.formula && ` · ${metric.formula}`}{metric?.input_refs?.map((ref) => <button key={ref} className={`ml-2 ${evidenceLinkClass}`} onClick={() => onEvidence(ref)}>{ref}</button>)}</p> })}{claim.rendered_source_fields?.map((field) => <p key={field.ref} className="break-words text-xs"><strong>Source field {field.ref}:</strong> {field.value}</p>)}</article>)}
      {output?.hypotheses?.map((item, index) => <div key={index} className="space-y-1 text-xs"><p><strong>Counterevidence:</strong> {item.counterevidence_ids.join(', ') || 'None cited'}</p><p><strong>Limitations:</strong> {item.limitations.join('; ')}</p><p><strong>Next checks:</strong> {item.next_checks.join('; ')}</p></div>)}
      {output?.assertions?.map((item, index) => <div key={index} className="space-y-1 text-xs"><blockquote className="border-l-2 pl-2">{item.source_span}</blockquote><p>Source: {item.source_id} · Mentioned: {item.mentioned_entities.join(', ')}</p><p>Uncertainty: {item.uncertainty}</p></div>)}
      {output?.proposals?.map((item, index) => <div key={index} className="space-y-2 border-t py-4 text-sm"><p>{item.catalog_action_id} · {item.owner_role}</p><p className="text-xs">Prerequisites: {item.prerequisites.join('; ')}</p><div className="flex gap-2">{item.evidence_ids.map((id) => <button key={id} className={evidenceLinkClass} onClick={() => onEvidence(id)}>{id}</button>)}</div><p className="text-xs text-amber-900">Draft recommendation · requires a version-bound human review.</p></div>)}
      {[...(output?.limitations ?? []), ...(output?.abstention_reasons ?? []), ...(output?.unresolved_issues ?? []), ...(current.result?.validation?.errors ?? [])].map((item, index) => <p key={index} className="text-xs text-amber-900">{item}</p>)}
      {output && <ReviewPublication key={current.id} run={current} />}
      {current.task === 'note' && output && <p className="text-xs text-amber-900">Extracted assertions are drafts. An owner must confirm the source and import it before it becomes incident evidence.</p>}
    </div>}
  </section>
}


function ReviewPublication({ run }: { run: AiRun }) {
  const mutation = useMutation({ mutationFn: (body: AiReviewPublicationRequest) => incidentApi.publishAiReview(run.id, body), retry: false })
  if (!run.output_digest) return <p className="text-xs text-amber-900">This run did not supply an output digest. Reload its stored identity before recording semantic review.</p>
  return <div className="space-y-3 border-t pt-4"><p className="text-xs leading-5 text-zinc-600">Sharing makes this exact output and its cited records accessible to invited reviewers. Publication does not approve a recovery action.</p>
    <Button size="sm" variant="outline" disabled={mutation.isPending || mutation.isSuccess} onClick={() => { const body = mutation.isError ? mutation.variables : { output_digest: run.output_digest ?? '', idempotency_key: crypto.randomUUID() }; if (body) mutation.mutate(body) }}>{mutation.isPending ? 'Publishing review packet…' : mutation.isSuccess ? 'Published for reviewer inbox' : mutation.isError ? 'Retry same review publication' : 'Publish draft for reviewer inbox'}</Button>
    {mutation.error && <p role="alert" className="text-xs text-red-800">{mutation.error.message} Retry preserves the exact output identity and request key.</p>}
    {mutation.isSuccess && <p role="status" className="text-xs text-emerald-800">Draft published for authenticated review. Independence still requires a reviewer declaration and is not externally verified.</p>}
    <SemanticRunReview key={run.id} runId={run.id} selfReview />
  </div>
}

export function PrecedentConditions({ item }: { item: Pick<IncidentSearchResult, 'comparison_facts' | 'missing_information' | 'historical_prerequisites' | 'current_prerequisites'> }) {
  return <div className="space-y-2 text-xs leading-5">{item.comparison_facts?.length ? <div><h4 className="font-medium">Recorded operational comparison</h4><ul className="list-disc pl-4">{item.comparison_facts.map((fact, index) => <li key={index}>{fact}</li>)}</ul></div> : null}{item.missing_information?.length ? <p className="text-amber-900"><strong>Missing comparison evidence:</strong> {item.missing_information.join('; ')}</p> : null}{item.historical_prerequisites?.length ? <p><strong>Historical action prerequisites:</strong> {item.historical_prerequisites.join('; ')}</p> : null}{item.current_prerequisites?.length ? <p><strong>Current prerequisites to verify:</strong> {item.current_prerequisites.join('; ')}</p> : null}</div>
}

export function HybridPanel({ report, enabled }: { report: AnalysisReport; enabled: boolean }) {
  const [query, setQuery] = useState(report.summary)
  const [corpusId, setCorpusId] = useState('')
  const corpora = useQuery({ queryKey: ['corpora'], queryFn: incidentApi.corpora, enabled })
  const selected = corpusId || corpora.data?.items[0]?.id || ''
  const search = useMutation({ mutationFn: () => incidentApi.hybridSearch({ query, corpus_id: selected, cutoff: report.cutoff, exclude_id: report.incident_id, idempotency_key: crypto.randomUUID() }) })
  return <section className="space-y-4 rounded-lg border bg-card p-5"><h2 className="font-semibold">Hybrid precedent search</h2>{enabled ? <><label className="block text-xs">Pinned corpus<select className={selectClass} value={selected} disabled={corpora.isPending || !corpora.data?.items.length} onChange={(event) => setCorpusId(event.target.value)}>{!corpora.data?.items.length && <option value="">{corpora.isPending ? 'Loading corpus releases…' : 'No published corpus available'}</option>}{corpora.data?.items.map((item) => <option key={item.id} value={item.id}>{item.id}</option>)}</select></label><label className="block text-xs">Search evidence<Input value={query} onChange={(event) => setQuery(event.target.value)} /></label><Button size="sm" disabled={!selected || !query.trim() || search.isPending} onClick={() => search.mutate()}>{search.isPending ? 'Searching precedents…' : 'Search hybrid precedents'}</Button></> : <p className="text-xs text-zinc-600">Sign in with reviewer access and use an indexed corpus for semantic retrieval. Lexical precedents remain available below.</p>}{search.error && <p role="alert" className="text-xs text-red-700">{search.error.message}</p>}{search.data && <p className="text-xs text-zinc-500">Pinned release: {search.data.manifest.corpus_id} · cutoff: {search.data.manifest.cutoff}</p>}{search.data && search.data.results.length === 0 && <p role="status" className="border-t pt-4 text-sm text-muted-foreground">No useful precedent was found in this pinned corpus. Verify current conditions before borrowing an action.</p>}{corpora.isError && <p role="alert" className="text-xs text-red-800">Corpus releases could not be loaded: {corpora.error.message}</p>}{search.data?.results.map((item) => <article key={`${item.id}-${item.revision}`} className="space-y-2 border-t pt-3"><Link className="font-medium underline decoration-border underline-offset-4 hover:decoration-current focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring" to={`/incidents/${encodeURIComponent(item.id)}?revision=${item.revision}`}>{item.title}</Link><p className="text-xs">{item.match_reason}</p><p className="text-xs"><strong>Differences:</strong> {item.differences.join('; ')}</p><PrecedentConditions item={item} />{item.excerpts?.map((excerpt) => <blockquote key={excerpt.id} className="border-l border-border pl-3 text-xs leading-relaxed">{excerpt.text ?? excerpt.excerpt} · {excerpt.source_id ?? excerpt.id}</blockquote>)}</article>)}</section>
}
export function ExportReport({ report, enabled }: { report: AnalysisReport; enabled: boolean }) {
  const exportFile = useMutation({ mutationFn: () => incidentApi.exportReport(report.id), onSuccess: (blob) => { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${report.incident_id}-revision-${report.revision}.json`; link.click(); URL.revokeObjectURL(url) } })
  return <div><Button className="mt-3" size="sm" variant="outline" disabled={!enabled || exportFile.isPending} onClick={() => exportFile.mutate()}>{exportFile.isPending ? 'Preparing export…' : 'Export portable report'}</Button>{!enabled && <p className="mt-1 text-xs text-zinc-500">Reviewer sign-in required for export.</p>}{exportFile.error && <p role="alert" className="text-xs text-red-700">{exportFile.error.message}</p>}</div>
}
