import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { useAuth } from '@/components/Auth'
import { Button } from '@/components/ui/button'
import type { AnalysisReport, IncidentRevision } from '@/lib/incidents'
import { formatInstant } from '@/lib/status'
import { workflowApi } from '@/lib/workflow'

const words = (value: string) => value.replaceAll('_', ' ').toLowerCase()
const refs = (values: string[]) => values.length ? values.join(', ') : 'None recorded'

export function SupervisorReport({ report, incident, currentRevision }: { report: AnalysisReport; incident: IncidentRevision; currentRevision: number }) {
  const { user } = useAuth()
  const [expanded, setExpanded] = useState(false)
  const enabled = !!user && report.execution_kind !== 'saved_deterministic'
  const workflow = useQuery({ queryKey: ['incident-workflow', report.incident_id, user?.id, currentRevision, report.revision], queryFn: () => workflowApi.get(report.incident_id), enabled, retry: false })
  const data = enabled ? workflow.data : undefined
  return <section className="supervisor-export rounded-lg border border-zinc-300 bg-white p-4 sm:p-6" aria-label="Supervisor report export">
    <div className="flex flex-wrap items-center justify-between gap-3 print:hidden"><div><h2 className="text-lg font-semibold">Supervisor report</h2><p className="mt-1 text-xs text-zinc-600">A readable report with sources, open questions and named actions. Use your browser’s print dialog to save a PDF.</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" aria-expanded={expanded} onClick={() => setExpanded(!expanded)}>{expanded ? 'Hide report preview' : 'Preview supervisor report'}</Button><Button size="sm" variant="outline" disabled={enabled && workflow.isPending} onClick={() => window.print()}>Print investigation report</Button></div></div>
    <article className={`supervisor-report mt-5 space-y-5 break-words text-sm leading-6 ${expanded ? '' : 'hidden print:block'}`} aria-label="Printable supervisor report">
      <header className="space-y-1 border-b border-zinc-300 pb-4"><h2 className="text-xl font-semibold">{incident.title}</h2><p>{incident.scope.factory} · Line {incident.scope.line_id} · {words(incident.scope.stage)} · {incident.scope.order_id} · {incident.scope.style_id}</p><p>{formatInstant(incident.window.start)} to {formatInstant(incident.window.end)}</p><p className="text-xs">FloorReplay · {incident.workspace_id && incident.workspace_id !== 'public-demo' ? 'Private workspace records' : 'Synthetic demonstration data'} · Times shown in India time</p><p className="text-xs break-all">Pinned report: {report.id} · Evidence revision {report.revision}</p><p>Evidence available by {formatInstant(report.cutoff)}. Records that arrived later are excluded from this calculation.</p></header>
      <section><h3 className="font-semibold">Findings from the recorded data</h3><p className="mt-2 whitespace-pre-wrap">{report.summary.replaceAll(/\bgood_units\b/g, 'good units')}</p><dl className="mt-3 grid gap-3 sm:grid-cols-3"><div><dt>Baseline planned</dt><dd className="font-semibold">{report.metrics.planned ?? 'Unavailable'} {words(report.metrics.unit)}</dd></div><div><dt>Recorded good output</dt><dd className="font-semibold">{report.metrics.observed ?? 'Unavailable'} {words(report.metrics.unit)}</dd></div><div><dt>Observed shortfall</dt><dd className="font-semibold">{report.metrics.shortfall ?? 'Unavailable'} {words(report.metrics.unit)}</dd></div></dl><p className="mt-2">Calculation coverage: {words(report.metrics.status)}. {report.metrics.missing_buckets.length} missing intervals; {report.metrics.unfinished_buckets.length} unfinished intervals. Missing data is not counted as zero.</p><p className="mt-2 text-xs">{report.metrics.formula ?? 'Calculation formula unavailable.'}</p><p className="text-xs">Calculation sources: {refs(report.metrics.inputs?.flatMap((input) => [input.plan.id, input.output.id]) ?? [])}</p></section>
      <section><h3 className="font-semibold">Possible explanations and uncertainty</h3><p>These are evidence-based possibilities, not confirmed causes. Calculation completion does not mean that an incident is resolved.</p>{report.hypotheses.length ? report.hypotheses.map((item, index) => <div className="mt-3 border-l-2 border-zinc-300 pl-3" key={`${item.category}-${index}`}><h4 className="font-medium">{words(item.category)} · {words(item.status)}</h4><p>{item.mechanism}</p><p className="text-xs">Supporting records: {refs(item.supporting_evidence)}. Contradicting records: {refs(item.contradicting_evidence)}.</p><p><strong>Next check:</strong> {item.next_check}</p></div>) : <p>No specific contributor is supported by the current evidence.</p>}{Object.entries(report.capabilities ?? {}).map(([name, capability]) => capability.reasons.length > 0 && <p className="mt-2" key={name}><strong>{words(name)}:</strong> {capability.reasons.join('; ')}</p>)}</section>
      <section><h3 className="font-semibold">Proposed actions and responsibility</h3><p>Proposal review records a decision; it does not prove an action was performed.</p>{report.proposals.length ? report.proposals.map((proposal) => <div className="mt-3 border-l-2 border-zinc-300 pl-3" key={proposal.id}><h4 className="font-medium">{words(proposal.type)}</h4><p>{proposal.purpose}</p><p>Responsible role: {words(proposal.owner_role)}. Review: {words(report.reviews?.filter((review) => review.proposal_id === proposal.id).at(-1)?.state ?? proposal.state)}.</p><p>Before acting: {refs(proposal.preconditions)}</p><p>Still needed: {refs(proposal.missing_information)}</p><p className="text-xs">Supporting records: {refs(proposal.supporting_evidence)}</p></div>) : <p>No recovery proposal is supported by this report.</p>}</section>
      <section><h3 className="font-semibold">Current action and resolution record</h3>{data ? <><p>Workflow snapshot retrieved {formatInstant(new Date(workflow.dataUpdatedAt).toISOString())}. Printing uses this loaded snapshot, separate from the pinned revision {report.revision} analysis. The snapshot’s current evidence revision is {data.current_revision}.</p>{workflow.isFetching && <p>Refreshing workflow; the previously loaded snapshot is shown.</p>}{workflow.isError && <p>Workflow refresh failed: {workflow.error.message}. This is the last loaded snapshot and may be out of date.</p>}<p><strong>Incident state:</strong> {words(data.resolution)}. {data.resolution_rationale ?? 'No resolution rationale recorded.'}</p>{data.tasks.length ? data.tasks.map((task) => <div className="mt-3 border-l-2 border-zinc-300 pl-3" key={task.id}><h4 className="font-medium">{task.question}</h4><p>Assigned to {task.assignee_name} · Due {formatInstant(task.due_at)} · {words(task.status)}{task.overdue ? ' · Overdue' : ''}</p><p className="text-xs break-all">Origin: revision {task.revision} · {task.analysis_id}</p>{task.response && <p>Source response: {task.response.summary} · {task.response.source_ref} · Evidence {task.response.evidence_id} in revision {task.response.revision}</p>}{task.outcome && <><p>Recorded action: {task.outcome.action_taken} · Completed {formatInstant(task.outcome.actual_completed_at)}</p><p>Outcome assessment: {task.outcome.assessment}. {task.outcome.observed_good_units !== null ? `Recorded output: ${task.outcome.observed_good_units} good units at ${task.outcome.observed_at ? formatInstant(task.outcome.observed_at) : 'an unspecified time'}.` : 'No post-action output measurement recorded.'}</p><p>Remaining uncertainty: {task.outcome.remaining_uncertainty}</p></>}</div>) : <p>No assigned checks recorded in the current workflow.</p>}<p className="mt-3">Handover: {data.handover.summary}</p><p>Handover uncertainties: {refs(data.handover.uncertainties)}</p></> : <p>{!enabled ? 'Current assignments, named owners and incident resolution are unavailable in this public or saved report. Sign in as an invited reviewer to include the current workflow.' : workflow.isError ? `Current workflow unavailable: ${workflow.error.message}. Assignment and resolution status cannot be established by this export.` : 'Loading current workflow. Assignment and resolution status have not yet been included.'}</p>}</section>
      <section><h3 className="font-semibold">Evidence record</h3><p>These observations belong to the pinned calculation. A source assertion remains an assertion until checked.</p>{report.timeline.length ? report.timeline.map((event) => <div key={event.id} className="mt-3 border-t border-zinc-200 pt-2"><p className="font-medium">{event.id} · {words(event.lane ?? event.type)}{event.assertion ? ' · Source assertion' : ''}</p><p>{formatInstant(event.occurred_at ?? event.start ?? '')}{event.end ? ` to ${formatInstant(event.end)}` : ''}</p><p>{event.summary}</p>{event.source_id && <p className="text-xs">Source: {event.source_id}</p>}</div>) : <p>No timeline observations available at the cutoff.</p>}</section>
      <footer className="border-t border-zinc-300 pt-3 text-xs">This export includes deterministic analysis and available workflow records. AI drafts require a separate factual-support review. Check prerequisites and local conditions before acting.</footer>
    </article>
  </section>
}
