"""import audits: raw bytes and publication records

Revision ID: 2331e274a192
Revises: 81689f7ef2c7
Create Date: 2026-09-27 22:45:57.397074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2331e274a192'
down_revision: Union[str, Sequence[str], None] = '81689f7ef2c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_audits',
    sa.Column('preview_digest', sa.String(length=80), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('raw_digest', sa.String(length=80), nullable=False),
    sa.Column('raw_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('blocking_issue_count', sa.Integer(), nullable=False),
    sa.Column('warning_issue_count', sa.Integer(), nullable=False),
    sa.Column('declared_evidence_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('coverage_complete', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshots.id'], ),
    sa.PrimaryKeyConstraint('preview_digest')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_audits')
    # ### end Alembic commands ###
