"""parser calls and review checks

Revision ID: 344843712202
Revises: 8edce5e5fb43
Create Date: 2026-09-27 23:34:21.042873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '344843712202'
down_revision: Union[str, Sequence[str], None] = '8edce5e5fb43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parser_calls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('note_digest', sa.String(length=80), nullable=False),
    sa.Column('parser_kind', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_digest', sa.String(length=80), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_checks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('original_replay_id', sa.String(length=64), nullable=False),
    sa.Column('target_scenario_id', sa.String(length=64), nullable=False),
    sa.Column('target_scenario_revision', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('changed_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_context_digest', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_checks_original_replay_id'), 'review_checks', ['original_replay_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_checks_original_replay_id'), table_name='review_checks')
    op.drop_table('review_checks')
    op.drop_table('parser_calls')
    # ### end Alembic commands ###
