"""initial schema: artifacts, scenarios, configurations, expectations, replay attempts

Revision ID: 81689f7ef2c7
Revises: 
Create Date: 2026-09-27 22:29:49.779723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81689f7ef2c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_digest', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_digest')
    )
    op.create_table('execution_configurations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('policy_kind', sa.String(length=32), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('known_limitation', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expectation_revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.String(length=64), nullable=False),
    sa.Column('assertions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'revision', 'configuration_id', name='uq_expectation')
    )
    op.create_table('replay_attempts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_revision', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.String(length=64), nullable=False),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('domain_outcome', sa.String(length=32), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expectation_verdict', sa.String(length=16), nullable=True),
    sa.Column('expectation_failures', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_digest', sa.String(length=80), nullable=True),
    sa.Column('manifest_digest', sa.String(length=80), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_replay_attempts_lifecycle'), 'replay_attempts', ['lifecycle'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('declared_evidence_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('coverage_complete', sa.Boolean(), nullable=False),
    sa.Column('content_digest', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_snapshots_kind'), 'source_snapshots', ['kind'], unique=False)
    op.create_table('scenario_revisions',
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('defect_statement', sa.Text(), nullable=False),
    sa.Column('event', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('catalog_revision_id', sa.String(length=64), nullable=False),
    sa.Column('pinned_snapshot_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['catalog_revision_id'], ['catalog_revisions.id'], ),
    sa.PrimaryKeyConstraint('scenario_id', 'revision')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_revisions')
    op.drop_index(op.f('ix_source_snapshots_kind'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_replay_attempts_lifecycle'), table_name='replay_attempts')
    op.drop_table('replay_attempts')
    op.drop_table('expectation_revisions')
    op.drop_table('execution_configurations')
    op.drop_table('catalog_revisions')
    # ### end Alembic commands ###
